/* global define */
/* eslint-disable key-spacing, quote-props*/
define({
  'TITLE'           : 'Preferences...',
  'CANCEL'          : 'Cancel',
  'SAVE'            : 'Save',
  'SEARCH'          : 'Search...',
  'SEARCH_TITLE'    : 'Regex based search',
  'SEARCH_CUSTOM'   : 'Custom search',
  'SYSTEM'          : 'System',
  'CHANGED'         : '* Review Changed',
  'EXTENSIONS'      : 'Extensions',
  'EDITOR'          : 'Editor',
  'LINTING'         : 'Linting',
  'CODE_FOLDING'    : 'Code Folding',
  'CODE_HINT'       : 'Code Hint',
  'NETWORK'         : 'Network',
  'OTHERS'          : 'Others',

  // Preferences strings
  // PROP_ + uppercase preference name
  'PROP_CLOSEBRACKETS'                  : 'Automatically close brackets, braces and parentheses',
  'PROP_CLOSEOTHERS.ABOVE'              : 'Close Others Above in Working file Context Menu',
  'PROP_CLOSEOTHERS.BELOW'              : 'Close Others Below in Working file Context Menu',
  'PROP_CLOSEOTHERS.OTHERS'             : 'Close Others in Working file Context Menu',
  'PROP_CLOSETAGS'                      : 'Close tags',
  'PROP_HEALTHDATA.HEALTHDATATRACKING'  : 'Track health data',
  'PROP_DRAGDROPTEXT'                   : 'Drag&drop text',
  'PROP_HIGHLIGHTMATCHES'               : 'Highlight matches',
  'PROP_INSERTHINTONTAB'                : 'Insert Hint on Tab',
  'PROP_MAXCODEHINTS'                   : 'Max code hints',
  'PROP_SCROLLPASTEND'                  : 'Scroll past end',
  'PROP_SHOWCODEHINTS'                  : 'Show code hints',
  'PROP_SHOWCURSORWHENSELECTING'        : 'Show cursor when selecting',
  'PROP_SHOWLINENUMBERS'                : 'Show line numbers',
  'PROP_SMARTINDENT'                    : 'Smart indent',
  'PROP_SOFTTABS'                       : 'Soft tabs',
  'PROP_SORTDIRECTORIESFIRST'           : 'Sort directories first',
  'PROP_SPACEUNITS'                     : 'Space units',
  'PROP_STYLEACTIVELINE'                : 'Style active line',
  'PROP_TABSIZE'                        : 'Tab size',
  'PROP_USETABCHAR'                     : 'Use tab char',
  'PROP_UPPERCASECOLORS'                : 'Uppercase colors in Inline Editor',
  'PROP_WORDWRAP'                       : 'Word wrap',
  'PROP_DEBUG.SHOWERRORSINSTATUSBAR'    : 'Show errors in status bar',
  'PROP_FINDINFILES.NODESEARCH'         : 'Node based search',
  'PROP_FINDINFILES.INSTANTSEARCH'      : 'Instant search',
  'PROP_FONTS.FONTSIZE'                 : 'Font size',
  'PROP_FONTS.FONTFAMILY'               : 'Font family',
  'PROP_THEMES.THEMESCROLLBARS'         : 'Theme scroll bar',
  'PROP_THEMES.THEME'                   : 'Theme'
});
